export enum States {
  MAIN_MENU_REGULAR,
  MAIN_MENU_ADMIN,
  LIST_QUESTIONARIES_MENU,
  SEARCH_QUESTIONARY_MENU,
  CREATE_QUESTIONARY_MENU,
  FILLIN_QUESTIONARY_MENU,
  USER_STATS_MENU,
  QUESTIONARY_STATS_MENU,
  SPECIFIC_QUESTIONARY_STATS_MENU,
  LOGIN_MENU,
  REGISTER_MENU,
  QUIT_APPLICATION,
}
